services:
  words-server:
    build: .
    image: words-server
    container_name: words-server
    ports:
      - "9999:9999"
    restart: "${XWORD_RESTART_POLICY:-unless-stopped}"
    volumes:
      - type: bind
        source: ${WORDS_VERSION_FILE_HOST}
        target: /app/version.txt
        read_only: true
